server:
  port: 80
  shutdown: graceful
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
          group: logMessageConsumers
        output:
          destination: queue.log.messages
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                username: admin
#                password: admin
#                virtual-host: /
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true
  lifecycle:
    timeout-per-shutdown-phase: 20s


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework: debug
