server:
  port: 80
spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true