server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    listener:
      type: simple
      simple:
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
        acknowledge-mode: manual
    template:
      mandatory: true