server:
  port: 1012
  shutdown: graceful
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
          group: logMessageConsumers
        output:
          destination: queue.log.messages
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    listener:
      type: simple
      simple:
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
        acknowledge-mode: manual
    template:
      mandatory: true

  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org:
      springframework: debug